name: .py to executable on Linux
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Build executable
        run: |
          pyinstaller --onefile main.py --name main-linux
      - name: Upload executable to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: main-linux
          path: dist/main-linux
          if-no-files-found: error
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # create a release tag (if it doesn't exist)
          git fetch --tags
          if ! git rev-parse v${{ github.run_number }} >/dev/null 2>&1; then
            git tag v${{ github.run_number }}
            git push origin v${{ github.run_number }}
          fi

          # create a release
          gh release upload v${{ github.run_number }} dist/main-linux --clobber