name: .py to executable on Windows
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Build executable
        run: |
          pyinstaller --onefile main.py --name main-windows
      - name: Upload executable to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: main-windows
          path: dist/main-windows.exe
          if-no-files-found: error
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v${{ github.run_number }} dist/main-windows.exe -t "Release v${{ github.run_number }} for Windows"